### 5.1

In [0]:
import numpy as np

In [0]:
a = np.array([1, 2, 3], float)
print(a)

[ 1.  2.  3.]


In [0]:
print(a[1])

2.0


In [0]:
print(a.shape)

(3,)


In [0]:
b = a * 2
print(b)

[ 2.  4.  6.]


In [0]:
c = a + 1
print(c)

[ 2.  3.  4.]


In [0]:
d = c + b
print(d)

[  4.   7.  10.]


In [0]:
d = np.subtract(b, c)
print(d)

[ 0.  1.  2.]


In [0]:
print(b - c)

[ 0.  1.  2.]


In [0]:
f = d.transpose()
print(d)

print("")
print(f)

[ 0.  1.  2.]

[ 0.  1.  2.]


In [0]:
i = 2
d[0] * f[0] + d[1] * f[1] + d[2] * f[2]

5.0

In [0]:
g = np.dot(f, d)
print(g)
print(np.dot(d, f))
d.shape, f.shape

5.0
5.0


((3,), (3,))

In [0]:
f * d

array([ 0.,  1.,  4.])

In [0]:
d * f

array([ 0.,  1.,  4.])

In [0]:
a = np.array([[1, 2, 3]], float)
print(a)
b = a.transpose()
print(b)

[[ 1.  2.  3.]]
[[ 1.]
 [ 2.]
 [ 3.]]


In [0]:
c = np.dot(a, b)
c

array([[ 14.]])

In [0]:
np.dot(b, a)

array([[ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 3.,  6.,  9.]])

In [0]:
a.shape, b.shape, c.shape

((1, 3), (3, 1), (1, 1))

### $5E =
5\begin{pmatrix}
1 & 0 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0\\
0 & 0 & 1 & 0 & 0\\
0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 1
\end{pmatrix}
$
### $(5E)^{-1} =
{1/5}\begin{pmatrix}
1 & 0 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0\\
0 & 0 & 1 & 0 & 0\\
0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 1
\end{pmatrix} 
$

In [0]:
A = 5 * np.identity(5)
print(A)

[[ 5.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.]
 [ 0.  0.  5.  0.  0.]
 [ 0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  5.]]


In [0]:
P = np.linalg.inv(A)
print(P)

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [ 0.   0.   0.   0.2  0. ]
 [ 0.   0.   0.   0.   0.2]]


### 5.2

In [0]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
print(a)
np.linalg.det(a)

[[ 1.  2.  3.]
 [ 4.  0.  6.]
 [ 7.  8.  9.]]


59.999999999999986

In [0]:
4 * 8 * 3 + 2 * 6 * 7 - 6 * 8 * 1 - 2 * 4 * 9

60

### 5.3

In [0]:
np.linalg.inv(a)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [0]:
c = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]], float)
print(c)
np.linalg.matrix_rank(b, 0.0001)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


1

In [0]:
np.linalg.matrix_rank(a, 0.0001)

3

### 5.4

In [0]:
f = np.array([1, 5])
d = np.array([2, 8])
np.dot(f, d)

42

In [0]:
np.dot(d, f)

42

### 5.5

In [0]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
v = np.cross(a, b)
print (np.inner(v, c))
w = np.cross(b, c)
print (np.inner(w, a))

228.5
228.5
