## Матрицы и векторы
### Определитель матрицы

In [0]:
import numpy as np

## $\det A = \left|
\begin{array}{cccc}
a_{00} & a_{01} & \ldots & a_{0n}\\
a_{10} & a_{11} & \ldots & a_{1n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n0} & a_{n1} & \ldots & a_{nn}
\end{array}
\right|= \sum_{k=0}^{n} (-1)^{k+0}a_{0k}M_k^0$


Минор элемента  $a_{ij}$ квадратной матрицы – это определитель этой матрицы, у которого отсутствует  i-я строка и  j-й столбец. 

In [0]:
a = np.array([[1, 2], [3, 4]])
print(a)
a[0, 0] * a[1, 1] - a[0, 1] * a[1, 0] 

[[1 2]
 [3 4]]


-2

In [0]:
np.linalg.det(a)

-2.0000000000000004

In [0]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(b)

6.6613381477509402e-16

## $\det A = \left|
\begin{array}{cccc}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}
\right|=
1\left| 
\begin{array}{cccc}
5 & 6\\ 
8 & 9
\end{array} 
\right|
-2\left| 
\begin{array}{cccc}
4 & 6\\ 
7 & 9
\end{array} 
\right|
+3\left| 
\begin{array}{cccc}
4 & 5\\ 
7 & 8
\end{array} 
\right|=0
$


In [0]:
1 * (5 * 9 - 6 * 8) - 2 * (4 * 9 - 6 * 7) + 3 * (4 * 8 - 5 * 7)

0

## $\det A = \sum_{k=0}^{n} (-1)^{k+i}a_{ik}M_k^i =  \sum_{k=0}^{n} a_{ik}A_{ik}$

### Свойства определителей
1. Определитель не меняется при транспонировании.

2. При перестановке двух соседних строк (столбцов) определитель меняет знак. 

3. Определитель с двумя одинаковыми строками (столбцами) равен нулю.

4. Общий множитель строки (столбца) можно выносить за знак определителя.
$\begin{vmatrix} 1 & 4 & 2\\ 0 & 2 & 0\\ -7 & 14 & -7 \end{vmatrix}=-7\cdot \begin{vmatrix} 1 & 4 & 2\\ 0 & 2 & 0\\ 1 & -2 & 1 \end{vmatrix}= -14\cdot \begin{vmatrix} 1 & 2 & 2\\ 0 & 1 & 0\\ 1 & -1 & 1 \end{vmatrix}$

5. Если все элементы некоторой строки (столбца) равны нулю, то определитель равен нулю.

6. Если все элементы двух строк (или двух столбцов) пропорциональны, то определитель равен нулю.

7. Если к элементам некоторой строки (столбца) прибавить соответствующие элементы другой строки (столбца), предварительно умножив их на одно и то же отличное от нуля число, то определитель не изменится.

In [0]:
np.linalg.det(b)

6.6613381477509402e-16

### Ранг матрицы
Если из матрицы вычеркнуть M столбцов и М строк, то определитель оставшейся матрицы называют минором порядка М исходной матрицы. 

Рангом матрицы называют наибольший из порядков отличных от нуля ее миноров.


In [0]:
np.linalg.matrix_rank(b, 0.0001)

2

In [0]:
f = np.array([[1, 2, 3], [4, 5, 6], [0, 8, 9], [10, 0, 12]])
print(f)
np.linalg.matrix_rank(f, 0.0001)

[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [10  0 12]]


3