### 1 Вычислите, по возможности не используя программирование: обратная матрица к (5Е), где Е – единичная матрица размера 5х5.

**Ответ**<br>
Свойства обратной матрицы: 
* (kA)^-1 = k^-1 * A^-1, где k - коэффициент при матрице А
* E^-1 = E<br>

Т.о. (5Е)^-1 = 1/5 * E


**Проверим**

In [11]:
import numpy as np
a = 5* np.identity(5)
b = np.linalg.inv(a)

print(b)
print(np.dot(a,b))

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 2 Вычислите определитель матрицы [[1,2,3],[4,0,6],[7,8,9]]

![](Lesson7_1_pic1.jpg)<br>
**Проверим**

In [12]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]], float)
det_a = np.linalg.det(a)
print(det_a)

59.999999999999986


### 3 Вычислите матрицу, обратную данной [[1,2,3],[4,0,6],[7,8,9]]

![](Lesson7_1_pic2.jpg)<br>
![](Lesson7_1_pic3.jpg)<br>
**Проверим**

In [6]:
a = np.array([[1,2,3],[4,0,6],[7,8,9]], float)
b = np.linalg.inv(a)
print(b)
print(np.dot(a,b))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
[[ 1.00000000e+00 -2.77555756e-17  5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  2.77555756e-17  1.00000000e+00]]


### 4 Приведите пример матрицы 4х4, ранг которой равен 1

**Ответ**<br>
Это матрица, все строки которой пропорциональны

In [13]:
a = np.array([[1,2,3,4],[2,4,6,8],[-1,-2,-3,-4],[0.5,1,1.5,2]])
print(a)
print(np.linalg.matrix_rank(a))

[[ 1.   2.   3.   4. ]
 [ 2.   4.   6.   8. ]
 [-1.  -2.  -3.  -4. ]
 [ 0.5  1.   1.5  2. ]]
1


### 5 Вычислите скалярное произведение двух векторов:  (1, 5)  и  (2, 8)

![](Lesson7_1_pic5.jpg)<br>
**Проверим**

In [14]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

a = np.array([1, 5])
b = np.array([2, 8])
print(np.vdot(a, b))

42


### 6 Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

![](Lesson7_1_pic6.jpg)<br>
**Проверим**

In [10]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
print(np.vdot(a, np.cross(b,c)))
print(np.vdot(c, np.cross(a,b)))

228.5
228.5
